server:
    port: 8765

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
    application:
      name: feign-service #\u6307\u660E\u5E94\u7528\u540D\u79F0\uFF08\u670D\u52A1\u4E0E\u670D\u52A1\u76F8\u4E92\u8C03\u7528\u6839\u636Ename\u5C5E\u6027\uFF09