server:
    port: 8762

eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka-server:8761/eureka/ #host需要修改为镜像名称

spring:
    application:
      name: one-service #指明应用名称（服务与服务相互调用根据name属性）