server:
  port: 8889

eureka:
    instance:
      hostname: localhost
    client:
      register-with-eureka: false # \u662F\u5426\u6CE8\u518C\u5230eureka
      fetch-registry: false # \u662F\u5426\u4ECEeureka\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F
      serviceUrl:
          # eureka\u670D\u52A1\u5668\u5730\u5740\uFF08\u6CE8\u610F\uFF1A\u5730\u5740\u6700\u540E\u9762\u7684 /eureka/ \u662F\u56FA\u5B9A\u503C\uFF09
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/