server:
    port: 8765

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
    application:
      name: feign-service #指明应用名称（服务与服务相互调用根据name属性）

feign:
    hystrix:
      enabled: true #开启feign断路器功能