server:
    port: 8761 # eureka默认端口：8761

eureka:
    instance:
      prefer-ip-address: true
    client:
      register-with-eureka: false # 是否注册到eureka
      fetch-registry: false # 是否从eureka获取注册信息

